on: [push]

env:
  INSTALLER_TIMEOUT: 10m

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      # https://github.com/actions/setup-node/issues/68#issuecomment-536238341
      - name: Patch node gyp on windows to support Visual Studio 2019
        if: runner.os == 'windows'
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
      - name: Install root project dependencies
        run: yarn
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test
